[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
  function = "sitemap"
  path = "/sitemap.xml"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200